<?php require_once __DIR__.'/layouts/header.php'; mostrarFlash(); ?>
<div class="d-flex justify-content-between align-items-end mb-4"><div><span class="eyebrow">Información institucional</span><h1 class="page-title mb-1">Reportes</h1><p class="text-muted mb-0">Indicadores consolidados de tutorías personales y grupales.</p></div><button class="btn btn-outline-secondary" onclick="window.print()"><i class="bi bi-printer me-1"></i>Imprimir</button></div>
<div class="row g-3 mb-4">
<?php foreach([['tutorias','Tutorías registradas','calendar-check'],['tutorias_personales','Tutorías personales','mortarboard'],['tutorias_grupales','Materias grupales','people'],['estudiantes_grupales','Estudiantes en grupos','person-vcard'],['promedio','Promedio evaluación','star-fill']] as $c): ?>
<div class="col-6 col-xl"><div class="metric-card"><div class="metric-icon bg-light text-primary"><i class="bi bi-<?=$c[2]?>"></i></div><div><div class="metric-value"><?= $c[0]==='promedio' ? number_format((float)$resumen[$c[0]],1) : e($resumen[$c[0]]) ?></div><div class="metric-label"><?=e($c[1])?></div></div></div></div>
<?php endforeach; ?>
</div>
<div class="row g-4">
  <div class="col-xl-7"><div class="card card-custom p-4"><h5 class="fw-bold">Actividad por materia</h5><p class="small text-muted">Incluye sesiones personales con materia y sesiones grupales de materias.</p><div style="height:360px"><canvas id="reportMaterias"></canvas></div></div></div>
  <div class="col-xl-5"><div class="card card-custom p-4"><h5 class="fw-bold">Actividad por tutor</h5><p class="small text-muted">Cantidad de sesiones asociadas a cada tutor.</p><div style="height:360px"><canvas id="reportTutores"></canvas></div></div></div>
</div>
<div class="row g-4 mt-1"><div class="col-lg-6"><div class="card card-custom p-4"><h5 class="fw-bold">Estados</h5><div class="row g-3 mt-1"><div class="col-6"><div class="p-3 bg-light rounded-3"><small class="text-muted">Solicitudes pendientes</small><div class="h4 mb-0"><?=e($resumen['pendientes'])?></div></div></div><div class="col-6"><div class="p-3 bg-light rounded-3"><small class="text-muted">Programadas / aprobadas</small><div class="h4 mb-0"><?=e($resumen['programadas'])?></div></div></div><div class="col-6"><div class="p-3 bg-light rounded-3"><small class="text-muted">Realizadas</small><div class="h4 mb-0"><?=e($resumen['realizadas'])?></div></div></div><div class="col-6"><div class="p-3 bg-light rounded-3"><small class="text-muted">Canceladas</small><div class="h4 mb-0"><?=e($resumen['canceladas'])?></div></div></div></div></div></div><div class="col-lg-6"><div class="card card-custom p-4"><h5 class="fw-bold">Lectura rápida</h5><p class="text-muted small mb-2">Las cifras del informe se calculan desde la base consolidada del sistema.</p><div class="small"><strong>Personal:</strong> <?=e($resumen['tutorias_personales'])?> · <strong>Grupal:</strong> <?=e($resumen['tutorias_grupales'])?><br><strong>Estudiantes vinculados a grupos:</strong> <?=e($resumen['estudiantes_grupales'])?></div></div></div></div>
<script>
(function(){if(!window.Chart)return;const common={responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}}};new Chart(document.getElementById('reportMaterias'),{type:'bar',data:{labels:<?=json_encode($graficoMaterias['labels'],JSON_UNESCAPED_UNICODE)?>,datasets:[{label:'Tutorías',data:<?=json_encode($graficoMaterias['data'])?>}]},options:{...common,indexAxis:'y',scales:{x:{beginAtZero:true,ticks:{precision:0}}}}});new Chart(document.getElementById('reportTutores'),{type:'bar',data:{labels:<?=json_encode($graficoTutores['labels'],JSON_UNESCAPED_UNICODE)?>,datasets:[{label:'Sesiones',data:<?=json_encode($graficoTutores['data'])?>}]},options:{...common,scales:{y:{beginAtZero:true,ticks:{precision:0}}}}});})();
</script>
<style>@media print{.navbar,.btn,footer{display:none!important}main{padding:0!important}.card-custom{box-shadow:none;border:1px solid #ddd}}</style>
<?php include __DIR__.'/layouts/footer.php'; ?>
